## Naive Baye's Machine Learning Algorithms Implementation

In [1]:
from sklearn.datasets import load_iris

In [2]:
from sklearn.model_selection import train_test_split

In [3]:
X,y = load_iris(return_X_y=True)

In [4]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [5]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [13]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.30,random_state=0)

In [14]:
X_train

array([[5. , 2. , 3.5, 1. ],
       [6.5, 3. , 5.5, 1.8],
       [6.7, 3.3, 5.7, 2.5],
       [6. , 2.2, 5. , 1.5],
       [6.7, 2.5, 5.8, 1.8],
       [5.6, 2.5, 3.9, 1.1],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.3, 4.7, 1.6],
       [5.5, 2.4, 3.8, 1.1],
       [6.3, 2.7, 4.9, 1.8],
       [6.3, 2.8, 5.1, 1.5],
       [4.9, 2.5, 4.5, 1.7],
       [6.3, 2.5, 5. , 1.9],
       [7. , 3.2, 4.7, 1.4],
       [6.5, 3. , 5.2, 2. ],
       [6. , 3.4, 4.5, 1.6],
       [4.8, 3.1, 1.6, 0.2],
       [5.8, 2.7, 5.1, 1.9],
       [5.6, 2.7, 4.2, 1.3],
       [5.6, 2.9, 3.6, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [6.1, 3. , 4.6, 1.4],
       [7.2, 3.2, 6. , 1.8],
       [5.3, 3.7, 1.5, 0.2],
       [4.3, 3. , 1.1, 0.1],
       [6.4, 2.7, 5.3, 1.9],
       [5.7, 3. , 4.2, 1.2],
       [5.4, 3.4, 1.7, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [6.9, 3.1, 4.9, 1.5],
       [4.6, 3.1, 1.5, 0.2],
       [5.9, 3. , 5.1, 1.8],
       [5.1, 2.5, 3. , 1.1],
       [4.6, 3.4, 1.4, 0.3],
       [6.2, 2

In [15]:
from sklearn.naive_bayes import GaussianNB

In [16]:
gnb=GaussianNB()

In [17]:
gnb.fit(X_train,y_train)

GaussianNB()

In [18]:
y_pred=gnb.predict(X_test)

In [19]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [20]:
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[16  0  0]
 [ 0 18  0]
 [ 0  0 11]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      1.00      1.00        18
           2       1.00      1.00      1.00        11

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



In [27]:
import seaborn as sns
import pandas as pd
import numpy as np

In [28]:
df=sns.load_dataset('tips')

In [29]:
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [30]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   total_bill  244 non-null    float64 
 1   tip         244 non-null    float64 
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64   
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB


In [34]:
df['sex'].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [32]:
df['Sex']=np.where(df['sex']=='Male', 1, 0)

In [38]:
df.drop('sex',inplace=True,axis=1)

KeyError: "['sex'] not found in axis"

In [39]:
df.head()

total_bill   tip smoker  day    time  size  Sex
0       16.99  1.01     No  Sun  Dinner     2    0
1       10.34  1.66     No  Sun  Dinner     3    1
2       21.01  3.50     No  Sun  Dinner     3    1
3       23.68  3.31     No  Sun  Dinner     2    1
4       24.59  3.61     No  Sun  Dinner     4    0

In [40]:
df['smoker'].value_counts()

smoker
No     151
Yes     93
Name: count, dtype: int64

In [41]:
df['Smoker']=np.where(df['smoker']=='Yes', 1, 0)
df.drop('smoker',axis=1,inplace=True)

In [43]:
df.tail()

total_bill   tip   day    time  size  Sex  Smoker
239       29.03  5.92   Sat  Dinner     3    1       0
240       27.18  2.00   Sat  Dinner     2    0       1
241       22.67  2.00   Sat  Dinner     2    1       1
242       17.82  1.75   Sat  Dinner     2    1       0
243       18.78  3.00  Thur  Dinner     2    0       0

In [44]:
df['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [46]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['time_encoded'] = le.fit_transform(df['time'])

In [48]:
le1 = LabelEncoder()
df['Day'] = le1.fit_transform(df['day'])

In [50]:
df.tail()

total_bill   tip   day    time  size  Sex  Smoker  time_encoded  Day
239       29.03  5.92   Sat  Dinner     3    1       0             0    1
240       27.18  2.00   Sat  Dinner     2    0       1             0    1
241       22.67  2.00   Sat  Dinner     2    1       1             0    1
242       17.82  1.75   Sat  Dinner     2    1       0             0    1
243       18.78  3.00  Thur  Dinner     2    0       0             0    3

In [51]:
df.drop(['time','day'],axis=1,inplace=True)

In [52]:
df.tail()

total_bill   tip  size  Sex  Smoker  time_encoded  Day
239       29.03  5.92     3    1       0             0    1
240       27.18  2.00     2    0       1             0    1
241       22.67  2.00     2    1       1             0    1
242       17.82  1.75     2    1       0             0    1
243       18.78  3.00     2    0       0             0    3

In [54]:
X = df[['total_bill','tip','Sex','Smoker','Day','size']]
y = df['time_encoded']

In [45]:
from sklearn.model_selection import train_test_split

In [55]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [56]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [57]:
from sklearn.naive_bayes import GaussianNB

In [58]:
gnb = GaussianNB()

In [59]:
gnb.fit(X_train,y_train)

GaussianNB()

In [60]:
y_pred=gnb.predict(X_test)

In [61]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [62]:
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.9387755102040817
[[33  1]
 [ 2 13]]
              precision    recall  f1-score   support

           0       0.94      0.97      0.96        34
           1       0.93      0.87      0.90        15

    accuracy                           0.94        49
   macro avg       0.94      0.92      0.93        49
weighted avg       0.94      0.94      0.94        49

